---
- name: oh my zsh is install
  ansible.builtin.stat:
    path: '{{ ansible_env.HOME }}/.oh-my-zsh'
  register: is_installed

- name: install oh my zsh
  ansible.builtin.shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  when: not is_installed.stat.exists

- name: Include vars of stuff.yaml into the 'stuff' variable (2.2).
  ansible.builtin.include_vars:
    file: ../../homebrew/vars/main.yml
    name: homebrew

- ansible.builtin.set_fact: "installed_brew_packages={{ homebrew.cask_list + homebrew.cli_list }}"

- ansible.builtin.set_fact: "old_zshrc_conent={{ lookup('file', ansible_env.HOME + '/.zshrc') }}"

- name: replace .zshrc file
  ansible.builtin.template:
    src: zshrc-template.j2
    dest: '{{ ansible_env.HOME }}/.zshrc'
  when: '"gnzh" not in old_zshrc_conent'
  vars:
    installed_brew_packages: "{{ installed_brew_packages }}"

- name: check the .vimrc exists
  ansible.builtin.stat:
    path: '{{ ansible_env.HOME }}/.vimrc'
  register: vimrc

- name: replace .vimrc file
  ansible.builtin.template:
    src: vimrc-template.j2
    dest: '{{ ansible_env.HOME }}/.vimrc'
  when: not vimrc.stat.exists
