---
# tasks file for homebrew
- name: save homebrew repo directory
  ansible.builtin.command: brew --repo
  register: homebrew_repo_dir

- name: change homebrew repo source to tsinghua
  ansible.builtin.include_tasks: change_remote_url.yml
  vars:
    directory: '{{ item.directory }}'
    remote:
      name: '{{ item.remote.name }}'
      url: '{{ item.remote.url }}'
  with_items:
    - directory: '{{ homebrew_repo_dir.stdout_lines[0] }}'
      remote:
        name: origin
        url: https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/brew.git
    - directory: '{{ homebrew_repo_dir.stdout_lines[0] }}/Library/Taps/homebrew/homebrew-core'
      remote:
        name: origin
        url: https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-core.git
    - directory: '{{ homebrew_repo_dir.stdout_lines[0] }}/Library/Taps/homebrew/homebrew-cask'
      remote:
        name: origin
        url: https://mirrors.ustc.edu.cn/homebrew-cask.git

- ansible.builtin.include_tasks: install_cask.yml
  vars:
    name: '{{ cask_list }}'

- ansible.builtin.include_tasks: install_cli.yml
  vars:
    name: '{{ cli_list }}'

- name: change homebrew repo source to github
  ansible.builtin.include_tasks: change_remote_url.yml
  vars:
    directory: '{{ item.directory }}'
    remote:
      name: '{{ item.remote.name }}'
      url: '{{ item.remote.url }}'
  with_items:
    - directory: '{{ homebrew_repo_dir.stdout_lines[0] }}'
      remote:
        name: origin
        url: https://github.com/Homebrew/brew
    - directory: '{{ homebrew_repo_dir.stdout_lines[0] }}/Library/Taps/homebrew/homebrew-core'
      remote:
        name: origin
        url: https://github.com/Homebrew/homebrew-core
    - directory: '{{ homebrew_repo_dir.stdout_lines[0] }}/Library/Taps/homebrew/homebrew-cask'
      remote:
        name: origin
        url: https://github.com/Homebrew/homebrew-cask
