---
# vars file for homebrew
cask_list:
  - iterm2
  - lastpass
  - qqmusic
  - visual-studio-code
  - zoom
  - intellij-idea
  - sogouinput
  - postman
  - ticktick
  - wechat
  - wechatwork
  - ccleaner
  - slack
  - google-chrome
  - virtualbox
  - vagrant
  - raycast
  - netnewswire

cli_list:
  - warrensbox/tap/tfswitch
  - jenv
  - nvm
  - autojump
  - kubectl
  - zsh-autosuggestions
  - zsh-syntax-highlighting
  - watch
  - wget
  - graphviz
  - tmpwatch
  - jq
  - yq
  - tmux
  - go
  - tree
  - expect
  - zsh
  - openjdk
  - colima
  - docker
  - docker-compose
  - gnu-sed
  - pyenv

# the value should pass from --extra-vars
sudo_password: ''
